---
- name: Create destination directory for static site
  ansible.builtin.file:
    path: "{{ static_site_dest_dir }}"
    state: directory
    owner: www-data # Or whatever user Nginx runs as!
    group: www-data # Same for the group!
    mode: '0755'
  tags:
    - app
    - deploy

- name: Upload static site tarball
  ansible.builtin.copy:
    src: "{{ static_site_tarball }}"
    dest: "/tmp/{{ static_site_tarball | basename }}" # Sending it to /tmp first
    mode: '0644'
  tags:
    - app
    - deploy

- name: Unarchive the static site
  ansible.builtin.unarchive:
    src: "/tmp/{{ static_site_tarball | basename }}"
    dest: "{{ static_site_dest_dir }}"
    remote_src: yes # Yep, the source is already on the remote machine now
    owner: www-data
    group: www-data
  tags:
    - app
    - deploy

- name: Remove uploaded tarball
  ansible.builtin.file:
    path: "/tmp/{{ static_site_tarball | basename }}"
    state: absent
  tags:
    - app
    - deploy
