---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  tags:
    - base
    - update

- name: Upgrade all installed packages
  ansible.builtin.apt:
    upgrade: dist
  tags:
    - base
    - update

- name: Install common utilities
  ansible.builtin.apt:
    name:
      - git
      - curl
      - wget
      - unzip
      - vim
      - htop
    state: present
  tags:
    - base
    - utilities

- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
  tags:
    - base
    - security

- name: Ensure Fail2Ban is running and enabled
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: yes
  tags:
    - base
    - security
